export {setProfileData} from './Profile/ProfileAction';
export {setHomeData} from './Home/HomeAction';
export {setBookingData} from './MyBookinglist/MyBookinglistAction'
export {setVaccinelistData} from './Vaccinelist/VaccineListAction'
export {setTravelhistoryData} from './TravelHistoryList/TravelHistoryAction'
export {setInsuranceinfolistData} from './InsuranceInfoList/InsuranceInfoAction'
export {setGetdoc} from './Getdocbyid/GetdocbyidAction'
export {setTraveldoc} from './TravelDoc/TravelDocAction'
export {setselectlanguage} from './SelectLanguage/SelectLanguageAction'